/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_app1 (void);
GtkWidget* create_open_dialog (void);
GtkWidget* create_about2 (void);
GtkWidget* create_fontselectiondialog1 (void);
