/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

#include <nemesi/egui.h>
#include <nemesi/etui.h>

int gui(struct RTSP_args *rtsp_args, NMSUiHints *ui_hints, int argc, char *argv[])
{
  GtkWidget *nemesi;

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  save_rtsp_args(rtsp_args);
	if (ui_hints->url) {
		nmsprintf(1, "Connect: Please wait, opening \"%s\"", ui_hints->url);
		send_open(rtsp_args, ui_hints->url);
		gui_throbber(rtsp_args);
	} else
		nmsprintf(1, "Please, enter a command or press 'h' for help\n\n");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  nemesi = create_nemesi ();
  gtk_widget_show (nemesi);

  gtk_main ();
  return 0;
}

