/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_nemesi (void)
{
  GtkWidget *nemesi;
  GtkWidget *vbox1;
  GtkWidget *handlebox2;
  GtkWidget *menubar;
  GtkWidget *menuitem1;
  GtkWidget *menu1;
  GtkWidget *new1;
  GtkWidget *open1;
  GtkWidget *save1;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem2;
  GtkWidget *menu2;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem3;
  GtkWidget *menu3;
  GtkWidget *menuitem4;
  GtkWidget *menu4;
  GtkWidget *about1;
  GtkWidget *statusbar;
  GtkWidget *handlebox1;
  GtkWidget *hbox2;
  GtkWidget *toolbar1;
  GtkWidget *open_cmd;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *toggle_play_pause;
  GtkWidget *stop_cmd;
  GtkWidget *close_cmd;
  GtkWidget *hscale2;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  nemesi = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (nemesi, "nemesi");
  gtk_window_set_title (GTK_WINDOW (nemesi), "NeMeSi");
  gtk_window_set_resizable (GTK_WINDOW (nemesi), FALSE);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (nemesi), vbox1);

  handlebox2 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox2, "handlebox2");
  gtk_widget_show (handlebox2);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  menubar = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar, "menubar");
  gtk_widget_show (menubar);
  gtk_container_add (GTK_CONTAINER (handlebox2), menubar);

  menuitem1 = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_set_name (menuitem1, "menuitem1");
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem1);

  menu1 = gtk_menu_new ();
  gtk_widget_set_name (menu1, "menu1");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menu1);

  new1 = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (new1, "new1");
  gtk_widget_show (new1);
  gtk_container_add (GTK_CONTAINER (menu1), new1);

  open1 = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (open1, "open1");
  gtk_widget_show (open1);
  gtk_container_add (GTK_CONTAINER (menu1), open1);

  save1 = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (save1, "save1");
  gtk_widget_show (save1);
  gtk_container_add (GTK_CONTAINER (menu1), save1);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (save_as1, "save_as1");
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menu1), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu1), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quit1, "quit1");
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menu1), quit1);

  menuitem2 = gtk_menu_item_new_with_mnemonic ("_Edit");
  gtk_widget_set_name (menuitem2, "menuitem2");
  gtk_widget_show (menuitem2);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem2);

  menu2 = gtk_menu_new ();
  gtk_widget_set_name (menu2, "menu2");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem2), menu2);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_set_name (cut1, "cut1");
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menu2), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_set_name (copy1, "copy1");
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menu2), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_set_name (paste1, "paste1");
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menu2), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_set_name (delete1, "delete1");
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menu2), delete1);

  menuitem3 = gtk_menu_item_new_with_mnemonic ("_View");
  gtk_widget_set_name (menuitem3, "menuitem3");
  gtk_widget_show (menuitem3);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem3);

  menu3 = gtk_menu_new ();
  gtk_widget_set_name (menu3, "menu3");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem3), menu3);

  menuitem4 = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_set_name (menuitem4, "menuitem4");
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar), menuitem4);

  menu4 = gtk_menu_new ();
  gtk_widget_set_name (menu4, "menu4");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menu4);

  about1 = gtk_menu_item_new_with_mnemonic ("_About");
  gtk_widget_set_name (about1, "about1");
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menu4), about1);

  statusbar = gtk_statusbar_new ();
  gtk_widget_set_name (statusbar, "statusbar");
  gtk_widget_show (statusbar);
  gtk_box_pack_end (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_set_name (handlebox1, "handlebox1");
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (handlebox1), hbox2);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_set_name (toolbar1, "toolbar1");
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox2), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  open_cmd = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-open",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (open_cmd, "open_cmd");
  gtk_widget_show (open_cmd);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-go-forward", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  toggle_play_pause = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                "_Play",
                                NULL, NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_set_name (toggle_play_pause, "toggle_play_pause");
  gtk_widget_show (toggle_play_pause);

  stop_cmd = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-stop",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (stop_cmd, "stop_cmd");
  gtk_widget_show (stop_cmd);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  close_cmd = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-close",
                                NULL,
                                NULL, NULL, NULL, -1);
  gtk_widget_set_name (close_cmd, "close_cmd");
  gtk_widget_show (close_cmd);

  hscale2 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_set_name (hscale2, "hscale2");
  gtk_widget_show (hscale2);
  gtk_box_pack_start (GTK_BOX (hbox2), hscale2, TRUE, TRUE, 0);
  gtk_widget_set_size_request (hscale2, 271, 15);
  gtk_widget_set_sensitive (hscale2, FALSE);
  gtk_scale_set_value_pos (GTK_SCALE (hscale2), GTK_POS_LEFT);

  g_signal_connect ((gpointer) nemesi, "destroy",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) new1, "activate",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1, "activate",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1, "activate",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nemesi, nemesi, "nemesi");
  GLADE_HOOKUP_OBJECT (nemesi, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (nemesi, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (nemesi, menubar, "menubar");
  GLADE_HOOKUP_OBJECT (nemesi, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (nemesi, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (nemesi, new1, "new1");
  GLADE_HOOKUP_OBJECT (nemesi, open1, "open1");
  GLADE_HOOKUP_OBJECT (nemesi, save1, "save1");
  GLADE_HOOKUP_OBJECT (nemesi, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (nemesi, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (nemesi, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (nemesi, menuitem2, "menuitem2");
  GLADE_HOOKUP_OBJECT (nemesi, menu2, "menu2");
  GLADE_HOOKUP_OBJECT (nemesi, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (nemesi, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (nemesi, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (nemesi, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (nemesi, menuitem3, "menuitem3");
  GLADE_HOOKUP_OBJECT (nemesi, menu3, "menu3");
  GLADE_HOOKUP_OBJECT (nemesi, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (nemesi, menu4, "menu4");
  GLADE_HOOKUP_OBJECT (nemesi, about1, "about1");
  GLADE_HOOKUP_OBJECT (nemesi, statusbar, "statusbar");
  GLADE_HOOKUP_OBJECT (nemesi, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (nemesi, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (nemesi, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (nemesi, open_cmd, "open_cmd");
  GLADE_HOOKUP_OBJECT (nemesi, toggle_play_pause, "toggle_play_pause");
  GLADE_HOOKUP_OBJECT (nemesi, stop_cmd, "stop_cmd");
  GLADE_HOOKUP_OBJECT (nemesi, close_cmd, "close_cmd");
  GLADE_HOOKUP_OBJECT (nemesi, hscale2, "hscale2");

  gtk_window_add_accel_group (GTK_WINDOW (nemesi), accel_group);

  return nemesi;
}

