/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_nemesi (void);
GtkWidget* create_opendialog (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_info (void);
