.TH NeMeSI 1 "March 23, 2004"
.SH NAME
NeMeSI \- NEtwork MEdia Streamer I
.SH SYNOPSIS
.B nemesi 
.RB [ " options " ]
.RB [ " media URL " ]
.SS media URL
The URL of the multimedia file that you want enjoy.
.RS
.I Example:
.RS
nemesi rtsp://remotehost:port/media
.RE
.PP
.SH GENERAL OPTIONS
.TP
.B -h
List command-line options.
.TP
.B -V
Print version.
.TP
.B -v [n]
Set verbosity level
.TP
.B --gui
use Graphical User Interface.
.TP
.B --tui
use Textual User Interface (e-tui)
.SH GENERAL OUTPUT OPTIONS
.B --sysbuff <msec>
.RS
Set the
.B system buffer
cache of decoded milliseconds.
.RE
.TP
.B --noaudio
Do not inizialize audio output module
.TP
.B --novideo
Do not inizialize video output module
.TP
.B --nodisk
Do not inizialize diskwriter output module
.SH AUDIO OUTPUT OPTIONS
.B --ao <driver1[:device],driver2,...,[...]>
.RS
Specify a list of audio output drivers.
.RE
If the list ends with "..." then
.B NeMeSI
will also try the other installed audio drivers, not listed on the command line, if all
the provided drivers don't work.
.BR
.I NOTE:
Use --ao help to view the list of available audio drivers.
.
Available audio output drivers are:
.TP
.B sdl\ \ \ \ 
Highly platform independent SDL (Simple Directmedia Layer) library
output driver.
.TP
.B oss\ \ \ \ 
Open Sound System audio driver
.SH VIDEO OUTPUT OPTIONS
.B --vo <driver1[:option],driver2,...,[...]>
.RS
Specify a list of video output drivers.
.RE
If the list ends with "..." then
.B NeMeSI
will also try the other installes video drivers, not listed on the command line, if all
the provided drivers don't work.
.BR
.I NOTE:
Use --vo help to view the list of available video drivers.
.
Available video output drivers are:
.TP
.B sdl\ \ \ \ 
Highly platform independent SDL (Simple Directmedia Layer) library
output driver.
.SH DESCRIPTION
.B NeMeSI \-\- NEtwork MEdia Streamer I
is a streaming client that allows user to enjoy playback of multimedia files
with low latency transport over IP-based networks. This software is fully
compliant with all IETF's protocols for streaming data that requires real-time
class delivery. It also includes support for MP3 and GSM-AMR encoded stream.

.B NeMeSI
features an adaptive behaviour achieved by the innovative
.B Dynamic CoDec Switching
technique.

.B NeMeSI
is the official streaming client/player of
.B Open Media Streaming Project
by Internet Multimedia Group at Politecnico di Torino. Please visit
.B OMSP
home page (http://streaming.polito.it) for further information.

.SH USAGE
.SS Command line invocation
Normally
.B NeMeSI
is started with
.RS
.PP
nemesi
.I urlname
.RE
.PP
which runs
.B NeMeSi
and even try to open the URL described in
.IR "urlname".
This is equivalent to running
.B NeMeSI
in the command line
.RS
.PP
nemesi
.RE
.PP
and then issuing an open command
.RB "(" open " or " o ")"
at
.I More-Touch E-Tui
prompt (see
.B Textual User Interface
below) when
.B NeMeSI
is in the
.I INIT
state.

If the bootstrap phase executes whitout errors and the connection is
already established,
.B NeMeSI
provides the prompt in the
.I READY
state, ready to accept some command. It's a good idea to issue now a
.BR play " (or " p ")"
command to start the playback of the streaming session.

The playback can be paused with the command
.B zause
or stopped (which is like a pause plus a rewind) typing
.BR "stop".
The command
.B close
will end the connection with the streaming server and will return
.B NeMeSI
in the
.I INIT
state. A
.B quit
command exits
.B NeMeSI
and returns to the shell prompt.

.SS Bootstrap messages
The messages printed at bootstrap phase show
.IP \(bu 4
the names of the
.I plugins
loaded and the
.I RTP Payload Type
they manage
.IP \(bu 4
some informations about the setup of the audio and video drivers
.SS Textual user interface
.B NeMeSI
features the innovative
.I More-Touch Electric-Textual User Interface
for both prompting and parsing user commands. MT-ETUI accepts following commands:
.TP
.BR help " or " ?
print help
.TP
.BR quit
quit the program
.TP
.BR version
print informations about NeMeSI
.TP
.BR open "urlname"
connect to the urlname
.TP
.BR info
print info about the session
.TP
.BR play " [range]"
start the playback. The optional field
.I range
selects the start and stop time of the media to playback.
The format for
.I range
option is
.RS
.IP 
hh:mm:ss-HH:MM:SS
.RE
.IP
which instructs
.B NeMeSI
to start the playback of the stream at 
.I hh 
hours, 
.I mm 
minutes and 
.I ss
seconds and stop it at
.I HH
hours,
.I MM
minuts and
.I SS
seconds. Examples, showing
.B NeMeSI
prompt, of accepted command formats are:
.RS
.TP
.RB "[ READY ] " "play 20:10-1:4:50"
The playback starts at 20 minutes, 10 seconds and stops at 1 hour, 4 minutes and
50 seconds.
.TP 
.RB "[ READY ] " "play 15-"
The playback starts at 15 seconds and stops at the end (if any) of the stream.
.TP
.RB "[ READY ] " "play -25:6"
The playback starts at the very beginning of the stream and stops at 25 minutes and
6 seconds.
.RE
.TP
.BR zause
pause the playback
.TP
.BR stop
stop the playback
.TP
.BR close
close the connection
.TP
Every command accepts also its first char as abbreviation (e.g. 'h' for 'help').
.SH ENVIRONMENT
.TP
.B NEMESI_PLUGIN_DIR
Name of the alternative plugin directory. This should be an absolute path,
since you will probably invoke
.B NeMeSI
from different directories. The value of NEMESI_PLUGIN_DIR will be used 
instead of the compiled-in default.
.SH "EXIT STATUS"
.IP 0
No errors.
.IP 1
There were errors.
.SH "SEE ALSO"
NeMeSI documentation at Open Media Streaming Project home page
(http://streaming.polito.it).
.SH AUTHORS
.IP \(bu 2
Giampaolo
.B 'mancho'
Mancini
<giampaolo.mancini@polito.it>
.IP \(bu 2
Francesco
.B 'shawill'
Varano
<francesco.varano@polito.it>
.IP \(bu 2
Marco
.B 'sbiro'
Penno
<marco.penno@polito.it>
.TP
This manual page is written and maintained by
Giampaolo
.B 'mancho'
Mancini <giampaolo.mancini@polito.it>
.br
Francesco
.B 'shawill'
Varano <francesco.varano@polito.it>.

